### ISSUE TITLE
issue after checkout and start test

### ISSUE THREAD

**Issue by spham** [coding-with-dom/intro-to-nightwatchjs#2]
npm run test:cucumber

show issue

```

> intro-nightwtach@1.0.0 test:cucumber /Users/sylvain/intro-to-nightwatchjs
> cucumber-js --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty

Feature: Hacker News Search

  Scenario: Searching Hacker News
    Given I open Hacker News's home page
 Error while running .navigateTo() protocol action: invalid session id

 Error while running .locateMultipleElements() protocol action: invalid session id

 Error while running .locateMultipleElements() protocol action: invalid session id

 Error while running .locateMultipleElements() protocol action: invalid session id

 Error while running .getScreenshot() protocol action: invalid session id

   Creating screenshot was not successful. Response was:
  {
    status: -1,
    state: '',
    value: {
      message: 'invalid session id',
      error: [
        '  (Driver info: chromedriver=2.46.628411 ' +
          '(3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS ' +
          'X 10.12.6 x86_64)'
      ]
    },
    errorStatus: 6,
    error: 'invalid session id',
    httpStatusCode: 200
  }
   {
     status: -1,
     state: '',
     value: {
       message: 'invalid session id',
       error: [
         '  (Driver info: chromedriver=2.46.628411 ' +
           '(3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS ' +
           'X 10.12.6 x86_64)'
       ]
     },
     errorStatus: 6,
     error: 'invalid session id',
     httpStatusCode: 200
   }
       at processTicksAndRejections (internal/process/task_queues.js:89:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! intro-nightwtach@1.0.0 test:cucumber: `cucumber-js --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the intro-nightwtach@1.0.0 test:cucumber script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sylvain/.npm/_logs/2019-08-02T06_22_22_789Z-debug.log
```

**Comment by spham** [comment]
debug show as bellow

```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:cucumber'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.4.0
4 verbose run-script [ 'pretest:cucumber', 'test:cucumber', 'posttest:cucumber' ]
5 info lifecycle intro-nightwtach@1.0.0~pretest:cucumber: intro-nightwtach@1.0.0
6 info lifecycle intro-nightwtach@1.0.0~test:cucumber: intro-nightwtach@1.0.0
7 verbose lifecycle intro-nightwtach@1.0.0~test:cucumber: unsafe-perm in lifecycle true
8 verbose lifecycle intro-nightwtach@1.0.0~test:cucumber: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sylvain/intro-to-nightwatchjs/node_modules/.bin:/usr/local/opt/php@7.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sylvain/anaconda3/bin:/Users/sylvain/anaconda3/condabin:/usr/local/opt/php@7.2/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
9 verbose lifecycle intro-nightwtach@1.0.0~test:cucumber: CWD: /Users/sylvain/intro-to-nightwatchjs
10 silly lifecycle intro-nightwtach@1.0.0~test:cucumber: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cucumber-js --require cucumber.conf.js --require ' +
10 silly lifecycle     'step-definitions --format ' +
10 silly lifecycle     'node_modules/cucumber-pretty'
10 silly lifecycle ]
11 silly lifecycle intro-nightwtach@1.0.0~test:cucumber: Returned: code: 1  signal: null
12 info lifecycle intro-nightwtach@1.0.0~test:cucumber: Failed to exec test:cucumber script
13 verbose stack Error: intro-nightwtach@1.0.0 test:cucumber: `cucumber-js --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid intro-nightwtach@1.0.0
15 verbose cwd /Users/sylvain/intro-to-nightwatchjs
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "run" "test:cucumber"
18 verbose node v12.4.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error intro-nightwtach@1.0.0 test:cucumber: `cucumber-js --require cucumber.conf.js --require step-definitions --format node_modules/cucumber-pretty`
22 error Exit status 1
23 error Failed at the intro-nightwtach@1.0.0 test:cucumber script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by aberonni** [comment]
Hi, I suspect this is another example of https://github.com/mucsi96/nightwatch-api/issues/207

I would recommend following up there, in the meantime I will close this issue because I don't think it is related to the code in this repo. Please let me know if you disagree

**Comment by amyng56** [comment]
Hi, any update for this issue?

**Comment by aberonni** [comment]
As I mentioned in my comment above, I don't actually think this is an issue with this repo. However, updating the dependencies might help because I think it has been addressed in an upstream version of nightwatch.

If you would like to submit a PR that updates the version of nightwatch and nightwatch-api then that would be great. Hopefully that will fix this problem.
